import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 10-Jan-2020 08:43:44 PM'
'File path: /Volumes/MR.ZacK/USEFUL_BACKUP/SE/UATTests/ShippingState/ShippingState_UAT_Tests.html'
'Generated by: chatdanai374@gmail.com'
'----------------------------------------------------'

String baseUrl = "http://localhost:9000/db/login.jsp?jsessionid=4ca33f8ffc37df2bf8e2f6ca5afb3c0b"

WebUI.openBrowser(baseUrl)

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | http://localhost:9000/db/login.jsp?jsessionid=4ca33f8ffc37df2bf8e2f6ca5afb3c0b | "
selenium.open("http://localhost:9000/db/login.jsp?jsessionid=4ca33f8ffc37df2bf8e2f6ca5afb3c0b")

"click | //input[@value='Connect'] | "
selenium.click("//input[@value='Connect']")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=EMPOLYEEPOSITION | "
selenium.click("id=EMPOLYEEPOSITION")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | พนักงานจัดการพัสดุ"
selenium.type("name=r-1c2", "พนักงานจัดการพัสดุ")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=EMPOLYEE | "
selenium.click("id=EMPOLYEE")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | chatdanai374@gmail.com"
selenium.type("name=r-1c2", "chatdanai374@gmail.com")

"type | name=r-1c3 | Chatdanai Phakaket"
selenium.type("name=r-1c3", "Chatdanai Phakaket")

"type | name=r-1c4 | 1"
selenium.type("name=r-1c4", "1")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=STATUS | "
selenium.click("id=STATUS")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | พัสดุลงทะเบียน"
selenium.type("name=r-1c2", "พัสดุลงทะเบียน")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 2"
selenium.type("name=r-1c1", "2")

"type | name=r-1c2 | ยกเลิก"
selenium.type("name=r-1c2", "ยกเลิก")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 3"
selenium.type("name=r-1c1", "3")

"type | name=r-1c2 | เสร็จสิ้น"
selenium.type("name=r-1c2", "เสร็จสิ้น")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=STATION | "
selenium.click("id=STATION")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | มทส"
selenium.type("name=r-1c2", "มทส")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 2"
selenium.type("name=r-1c1", "2")

"type | name=r-1c2 | นครราชสีมา"
selenium.type("name=r-1c2", "นครราชสีมา")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 3"
selenium.type("name=r-1c1", "3")

"type | name=r-1c2 | เดอะมอลโคราช"
selenium.type("name=r-1c2", "เดอะมอลโคราช")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=MEMBER_TYPE | "
selenium.click("id=MEMBER_TYPE")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | test"
selenium.type("name=r-1c2", "test")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=MEMBER_LEVEL | "
selenium.click("id=MEMBER_LEVEL")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | test1"
selenium.type("name=r-1c2", "test1")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=MEMBER_CUSTOMER | "
selenium.click("id=MEMBER_CUSTOMER")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 100"
selenium.type("name=r-1c1", "100")

"type | name=r-1c2 | test test"
selenium.type("name=r-1c2", "test test")

"type | name=r-1c3 | 0987654321"
selenium.type("name=r-1c3", "0987654321")

"type | name=r-1c4 | 1"
selenium.type("name=r-1c4", "1")

"type | name=r-1c5 | 1"
selenium.type("name=r-1c5", "1")

"type | name=r-1c6 | 1"
selenium.type("name=r-1c6", "1")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=PACKAGETYPE | "
selenium.click("id=PACKAGETYPE")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | ttt"
selenium.type("name=r-1c2", "ttt")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=SENDINGTYPE | "
selenium.click("id=SENDINGTYPE")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 1"
selenium.type("name=r-1c1", "1")

"type | name=r-1c2 | 1"
selenium.type("name=r-1c2", "1")

"type | name=r-1c3 | 1"
selenium.type("name=r-1c3", "1")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=PACKAGING | "
selenium.click("id=PACKAGING")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 100"
selenium.type("name=r-1c1", "100")

"type | name=r-1c2 | 2020-01-10"
selenium.type("name=r-1c2", "2020-01-10")

"type | name=r-1c3 | 123 เดอะมอลโคราช"
selenium.type("name=r-1c3", "123 เดอะมอลโคราช")

"type | name=r-1c4 | test ผู้รับ"
selenium.type("name=r-1c4", "test ผู้รับ")

"type | name=r-1c5 | 10"
selenium.type("name=r-1c5", "10")

"type | name=r-1c6 | 10"
selenium.type("name=r-1c6", "10")

"type | name=r-1c7 | 1"
selenium.type("name=r-1c7", "1")

"type | name=r-1c8 | 1"
selenium.type("name=r-1c8", "1")

"type | name=r-1c9 | 1"
selenium.type("name=r-1c9", "1")

"type | name=r-1c10 | 1"
selenium.type("name=r-1c10", "1")

"type | name=r-1c11 | 100"
selenium.type("name=r-1c11", "100")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=SENTTIME | "
selenium.click("id=SENTTIME")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 100"
selenium.type("name=r-1c1", "100")

"type | name=r-1c2 | 09:00"
selenium.type("name=r-1c2", "09:00")

"type | name=r-1c3 | 10:00"
selenium.type("name=r-1c3", "10:00")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Clear'] | "
selenium.click("//input[@value='Clear']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=1 | "
selenium.selectFrame("index=1")

"click | id=SENTPARCEL | "
selenium.click("id=SENTPARCEL")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=2 | "
selenium.selectFrame("index=2")

"click | //input[@value='Run'] | "
selenium.click("//input[@value='Run']")

"selectFrame | relative=parent | "
selenium.selectFrame("relative=parent")

"selectFrame | index=3 | "
selenium.selectFrame("index=3")

"click | //input[@value='Edit'] | "
selenium.click("//input[@value='Edit']")

"click | //img[@alt='Add'] | "
selenium.click("//img[@alt='Add']")

"type | name=r-1c1 | 100"
selenium.type("name=r-1c1", "100")

"type | name=r-1c2 | 1"
selenium.type("name=r-1c2", "1")

"type | name=r-1c3 | 3"
selenium.type("name=r-1c3", "3")

"type | name=r-1c4 | 100"
selenium.type("name=r-1c4", "100")

"type | name=r-1c5 | 100"
selenium.type("name=r-1c5", "100")

"click | //img[@alt='Save'] | "
selenium.click("//img[@alt='Save']")

WebUI.closeBrowser()